[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "T201",   # print
    "T203",   # p-print
    "ERA001", # commented-out-code
    "FIX002", # line-contains-todo
    "TD002",  # missing-todo-author
    "TD003",  # missing-todo-link
    "S603",   # subprocess-without-shell-equals-true
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"*test*.py" = [
    "PT009", # pytest-unittest-assertion
    "S101",  # assert
]
